-- MySQL Script generated by MySQL Workbench
-- 05/05/16 00:08:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema passwordManager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema passwordManager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `passwordManager` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `passwordManager` ;

-- -----------------------------------------------------
-- Table `passwordManager`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passwordManager`.`user` (
  `username` (16) NOT NULL COMMENT '',
  `surname` (255) NULL COMMENT '',
  `password` (32) NOT NULL COMMENT '',
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '');


-- -----------------------------------------------------
-- Table `passwordManager`.`user_emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passwordManager`.`user_emails` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `user_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `user_id_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `passwordManager`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passwordManager`.`web_sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passwordManager`.`web_sites` (
  `web_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `url` VARCHAR(45) NOT NULL COMMENT '',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`web_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passwordManager`.`users_sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passwordManager`.`users_sites` (
  `user_sites_id` INT NOT NULL COMMENT '',
  `web_id` INT NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`user_sites_id`)  COMMENT '',
  INDEX `web_id_idx` (`web_id` ASC)  COMMENT '',
  CONSTRAINT `web_id`
    FOREIGN KEY (`web_id`)
    REFERENCES `passwordManager`.`web_sites` (`web_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_sites_id`)
    REFERENCES `passwordManager`.`user_emails` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
